# Generated by Django 3.1.5 on 2021-03-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userad_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userad',
            name='image1',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='userad',
            name='image2',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='userad',
            name='image3',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
