# Generated by Django 3.1.5 on 2021-03-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210323_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userad',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
