# Generated by Django 3.1.5 on 2021-03-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210323_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userad',
            name='km_driven',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='userad',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='userad',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userad',
            name='year',
            field=models.CharField(max_length=20),
        ),
    ]
