# Generated by Django 3.1.5 on 2021-03-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210323_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='userad',
            name='status',
            field=models.CharField(default='pending', max_length=10, null=True),
        ),
    ]
