# Generated by Django 3.1.5 on 2021-04-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_userad_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userad',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
