# Generated by Django 3.1.5 on 2021-04-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_userad_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userad',
            name='location_latitude',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userad',
            name='location_longitude',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
