# Generated by Django 3.1.5 on 2021-04-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_reportad'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
