# Generated by Django 3.1.5 on 2021-04-10 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_premiummember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premiummember',
            old_name='expiry_user',
            new_name='expiry_date',
        ),
    ]
