# Generated by Django 3.1.5 on 2021-04-13 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210410_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeturedAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField()),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userad')),
            ],
        ),
    ]
