# Generated by Django 3.1.5 on 2021-04-15 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_feturedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneToOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onetoone_requests_created', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onetoone_requests_reciever', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
