# Generated by Django 3.1.5 on 2021-04-16 05:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_onetoone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.date(2021, 4, 16))),
                ('message', models.TextField(null=True)),
                ('msg_type', models.CharField(max_length=15, null=True)),
                ('upload_file', models.FileField(default='', null=True, upload_to='files')),
                ('onetoone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.onetoone')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_requests_reciever', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_requests_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
