# Generated by Django 3.1.5 on 2021-04-16 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='upload_file',
            new_name='image',
        ),
    ]
