# Generated by Django 3.1.5 on 2021-04-20 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20210416_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetoone',
            name='ad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userad'),
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
