# Generated by Django 3.1.5 on 2021-04-21 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20210421_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 12, 20, 37, 145372)),
        ),
        migrations.AlterField(
            model_name='userad',
            name='fuel',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
