# Generated by Django 3.1.5 on 2021-04-21 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20210421_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 12, 23, 15, 433662)),
        ),
        migrations.AlterField(
            model_name='userad',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
