# Generated by Django 3.1.7 on 2021-04-28 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_auto_20210421_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='userad',
            name='brand_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userad',
            name='category_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 28, 17, 45, 35, 198425)),
        ),
    ]
